### ISSUE TITLE
Login and registeration system

### ISSUE THREAD

**Issue by MananJethwani** [BitByte-TPC/TPC-website#17]
As the TPC-website will now be serving as the gymkhana website we need to discuss the exact login method we are going to follow.

- I suggest the use of only college IDs so that no fake IDs can be created.

- other than that the basic method for login and registration will be as follows ->

1. In order for students to register they first need to login (this part will be created by @Aksh-Bansal-dev).
2. If someone is not logged in the registration form link should lead to the login page and if they are logged in the registration form will take them to the registration portal page.
3. The registration portal page will have a link to download the gymkhana form and a button to upload the filled form and a dropdown menu to select from the available list of clubs(if a user is redirected from a particular club's page then that particular clubs name should already be selected from the drop-down menu).
4. after all the required info is filled on the registration page they must be taken to a confirmation page showing all the final details.
5. If a user wishes to continue he/she will be taken to a payment portal(which will also generate a payment confirmation slip which will be stored in the database for further usage).
6. the registration portal will be designed by @harshit-2300

@garg3133 sir is this method fine with you?

**Comment by garg3133** [comment]
Yeah, seems good!

**Comment by Samy-33** [comment]
@Aksh-Bansal-dev, is this feature implemented? If yes, can you please close this issue?

**Comment by Aksh-Bansal-dev** [comment]
Yeah, this is done.
