### ISSUE TITLE
Spacing Issue in the Navbar And HomeNavBar on certain screen sizes

### ISSUE THREAD

**Issue by Lawful2002** [BitByte-TPC/TPC-website#19]
## Describe the bug
The spacing between the navbar menu items vanishes below a certain screen size. The home navbar item "Contact Us" gets split below certain screen sizes.

## Steps to reproduce the behavior:

1. Run the app
2. On the home page, reduce screen size until the issue is seen
3. Navigate to Projects/Domains, reduce screen size until the spacing vanishes

## Expected behavior

1. On the home navbar, the contents should not split onto 2 lines.
2. The spacing between menu items on the navbar should not vanish when the screen size is reduced.

## Environment (please complete the following information):

- OS: Windows 10
- Browser: Chrome

## Screenshots

![Screenshot (66)](https://user-images.githubusercontent.com/73544247/118814913-4aa47e00-b8ce-11eb-9419-3c3c887d5aa1.png)
![Screenshot (67)](https://user-images.githubusercontent.com/73544247/118814915-4c6e4180-b8ce-11eb-95b9-00f2f9629088.png)

**Comment by Lawful2002** [comment]
The home navbar issue


![Screenshot (68)](https://user-images.githubusercontent.com/73544247/118815012-690a7980-b8ce-11eb-989b-cc9a220ed85b.png)

**Comment by MananJethwani** [comment]
thanks, @Lawful2002 for the bug report.
