### ISSUE TITLE
grid system for project page

### ISSUE THREAD

**Issue by MananJethwani** [BitByte-TPC/TPC-website#21]
@Aksh-Bansal-dev currently if I open the project page projects are not displayed in a grid but in a list type format with each row consisting of only one card.
Please fix this in your next PR.

**Comment by Aksh-Bansal-dev** [comment]
The projects' page will show cards according to the width of your screen, so it will show only 1 card in one row on mobile and show 2 or 3+ cards on a wider screen.
![Screenshot (38)](https://user-images.githubusercontent.com/63552235/118838159-15eef180-b8e3-11eb-88e3-5fb22dee9608.png)

**Comment by MananJethwani** [comment]
@Aksh-Bansal-dev looks like a minor bug then!
![Screenshot from 2021-05-22 02-37-18](https://user-images.githubusercontent.com/50267986/119198294-b80b0700-baa6-11eb-83c1-534e6ea80109.png)

**Comment by MananJethwani** [comment]
looks like you fixed it in the current PR thanks.
