### ISSUE TITLE
setup backend and database

### ISSUE THREAD

**Issue by MananJethwani** [BitByte-TPC/TPC-website#3]
create a backend folder and setup django their as well as all the things required to connect to databse

**Comment by garg3133** [comment]
Don't create a folder for backend, keep the files in root directory itself.
Keeping backend files in a folder creates problem during production.

**Comment by somya51p** [comment]
@garg3133 sir I have added basic django structure in somya branch.....u may see once , further I will merge

**Comment by garg3133** [comment]
@somya51p Don't use names like `Prog_club` as project name, using `bitbyte` as project name is fine (all small letters and no underscores).
And in place of `bitbyte` app, you may use the `home`.

**Comment by garg3133** [comment]
Also, don't push migrations, pychache and db files. You may copy `.gitignore` from [here](https://github.com/garg3133/JagratiWebApp).

**Comment by somya51p** [comment]
Done.....the two branches can be merged now.

**Comment by garg3133** [comment]
Looks good! You may merge them now.
