### ISSUE TITLE
Responsiveness of home page

### ISSUE THREAD

**Issue by garg3133** [BitByte-TPC/TPC-website#32]
The home page of the website is currently not responsive and gets distorted on small screens:

* [ ] These headings are too big for a small screen, maybe the headings with font size ~3rem would be better for small screens.
  <img width="967" alt="image" src="https://user-images.githubusercontent.com/39924567/170889016-0746c32b-893c-45fe-a96d-50ea4fe48d81.png">

* [ ] The last few sections overlap with each other.
  <img width="969" alt="image" src="https://user-images.githubusercontent.com/39924567/170889140-c7df4a24-a409-4e0f-a03a-1ffa1f5bccc0.png">

**Comment by Rahul19241** [comment]
@garg3133 please assign this issue to me

**Comment by Rahul-Palahwat** [comment]
@garg3133 please assign this issue to me

**Comment by garg3133** [comment]
Sure @Rahul19241, you can take this.
