### ISSUE TITLE
Alignment issue on small screen

### ISSUE THREAD

**Issue by garg3133** [BitByte-TPC/TPC-website#37]
The content on small screens is not properly aligned.

* [ ] There seems to be a padding here on the left but not on the right, I think we can remove the padding from the left-side too
  <img width="964" alt="image" src="https://user-images.githubusercontent.com/39924567/170888917-c7c9bda7-58f0-442f-8954-7b14a3cc765a.png">
* [ ] In the sections below "ABOUT" too, there is padding on the left side while not on the right side. We should fix that too.

**Comment by Rahul-Palahwat** [comment]
@garg3133 assign this issue to me

**Comment by garg3133** [comment]
@Rahul19241 Not assigning this to you since you already have an issue assigned to you. Let's keep this open for someone else to take.
