### ISSUE TITLE
Add Patrons section on team page

### ISSUE THREAD

**Issue by garg3133** [BitByte-TPC/TPC-website#41]
We should also mention the name of our institute's director and the club's faculty in charge on the team page.

We can have them in the first row on the team page under the heading "Patrons" and then both coordinator and co-coordinator in the second row.

**Comment by a-Cash-dixit** [comment]
please assign this issue to me

**Comment by a-Cash-dixit** [comment]
![2022-05-31](https://user-images.githubusercontent.com/83697333/171101695-83b432a4-b2d7-4be2-b2e8-ceb0b0885e5b.png)

A. Director and Faculty do not have a github id. So we will exclude the github icon. if so how?
B. Images of director and Faculty in charge?

**Comment by garg3133** [comment]
A. Change the logic of the code to not include the Github icon if the GitHub link is not passed. @Aksh-Bansal-dev might be able to help.
B. You can take the pictures from here: https://faculty.iiitdmj.ac.in

Also, a few more things:
* Can you fix the shape of the profile images to be circular?
* Change "Coordinators" to "Office Bearers" and "coco" to "Co-coordinator".
* On Atul sir's card, change "Faculty" to "Faculty Incharge".

**Comment by Aksh-Bansal-dev** [comment]
> A. Director and Faculty do not have a github id. So we will exclude the github icon. if so how?

@a-Cash-dixit, you can just leave the github field empty and do something like this:

```typescript
{    
        github ? (
          <a href={github} target="_blank">
            <IconButton>
              <GitHub />
            </IconButton>
          </a>
        ) : null
}
```

**Comment by a-Cash-dixit** [comment]
thanks I will look into it.

**Comment by a-Cash-dixit** [comment]
@garg3133 thank you sir for the information. I will try to implement most of the above mentioned features.

**Comment by Samy-33** [comment]
> > A. Director and Faculty do not have a github id. So we will exclude the github icon. if so how?
> 
> @a-Cash-dixit, you can just leave the github field empty and do something like this:
> 
> ```tsx
> {    
>         github ? (
>           <a href={github} target="_blank">
>             <IconButton>
>               <GitHub />
>             </IconButton>
>           </a>
>         ) : null
> }
> ```

There's a concise way to do this:
```jsx
github && <a>...</a>
```

**Comment by a-Cash-dixit** [comment]
A)GithubUrl cannot be null(showing error) as it is in the interface of Domain Card as string so i have given it the value "#" for director and faculty in teamList and applied the condition in DomianCard.tsx. But keep getting these kind of errors as this is a typescript file. 
![2022-06-01](https://user-images.githubusercontent.com/83697333/171459895-436039f1-e095-42d8-8144-4397d8fc623a.png)
.

**Comment by garg3133** [comment]
@a-Cash-dixit I'm guessing dots in the prettier error are representing `space` character here. So, what it's trying to say here is to write your code like this:
```js
{githubProfileUrl != "#" && (
  <a href={githubProfileUrl} target="_blank">
    <IconButton>
      ....
    </IconButton>
  </a>
)}
```

Also, in the interface of Domain Card, you can just replace `githubProfileUrl: string` with `githubProfileUrl?: string` since `githubProfileUrl` is no longer required field.

**Comment by Aksh-Bansal-dev** [comment]
@a-Cash-dixit You can run `npm run lint:fix` or `npm run format` to fix those errors.

**Comment by a-Cash-dixit** [comment]
it worked in both the ways . thanks

**Comment by Samy-33** [comment]
> Also, in the interface of Domain Card, you can just replace `githubProfileUrl: string` with `githubProfileUrl?: string` since githubProfileUrl is no longer required field.


This is the preferred way.

**Comment by garg3133** [comment]
@a-Cash-dixit What's the status on this?

**Comment by a-Cash-dixit** [comment]
My laptop is gone for repair. You can assign someone else sir.

**Comment by arminpatel** [comment]
Can you assign this issue to me?

**Comment by arminpatel** [comment]
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/72291325/173601423-8b772057-89a5-44a9-a9e3-fc46a4b1c9e3.png">
Any social link I should add/remove? Any other suggestions?

The person icon links to the respective faculty profile on the institute website, like https://faculty.iiitdmj.ac.in/faculty/pnkondekar

**Comment by garg3133** [comment]
Looks good to me!
